In [5]:
import numpy as np


In [14]:
A = np.ones((4,4))
A[:,-1]=0
A[0,1]=0
A[1,2]=0
A[2,1]=0
A[2,2]=-1
A[3,1]=-1
A[3,2]=0
print(A)
np.linalg.det(A)

[[ 1.  0.  1.  0.]
 [ 1.  1.  0.  0.]
 [ 1.  0. -1.  0.]
 [ 1. -1.  0.  0.]]


0.0